#!/bin/sh

set -ex

export DIR=$(cd `dirname $0`; pwd)

ln -sfh ${DIR}/etc ${HOME}/.config

brew bundle check --verbose --file=${DIR}/share/Brewfile \
  || brew bundle install --verbose --file=${DIR}/share/Brewfile

rm -f ${DIR}/share/Brewfile.lock.json

grep -q /usr/local/bin/fish /etc/shells \
  || sudo bash -c 'echo /usr/local/bin/fish >> /etc/shells'

# https://stackoverflow.com/a/41553295
dscl . -read ~ UserShell | grep -q /usr/local/bin/fish \
  || chsh -s /usr/local/bin/fish

fish -c 'vim +PlugInstall +qall'

# https://github.com/Hammerspoon/hammerspoon/pull/582
fish -c "defaults write org.hammerspoon.Hammerspoon MJConfigFile $XDG_CONFIG_HOME/hammerspoon/init.lua"

osascript <<END
  tell application "Terminal"
    if the name of every settings set does not contain "Solarized Light" then
      do script "open '${DIR}/share/Solarized Light.terminal'"
    end if

    if the name of every settings set does not contain "Solarized Dark" then
      do script "open '${DIR}/share/Solarized Dark.terminal'"
    end if

    set default settings to settings set "Solarized Light"
  end tell
END
