#!/bin/bash

set -euo pipefail

DIR=$(cd "$(dirname "$0")"; pwd)

case `hostname` in
  "Matthews-Mac-Studio.local")
    profile="home"
    ;;

  *)
    echo `hostname`
    select profile in "home" "bridge" "stripe"; do
      case "$REPLY" in
        1|2|3) break;;
        *) continue;;
      esac
    done
    ;;
esac

echo "Using $profile profile..."

if [ ! -f "${DIR}/etc/git/profile" ]; then
  read -p "Set your git user.email: "
  git config --file "${DIR}/etc/git/profile" user.email "${REPLY}"
fi

mkdir -p "${HOME}/.local"

ln -sfh "${DIR}/bin" "${HOME}/.local/bin"
ln -sfh "${DIR}/etc" "${HOME}/.config"

which brew \
  || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew update --verbose
brew bundle install --cleanup --verbose --file="${DIR}/opt/Brewfile.${profile}"
brew cleanup --verbose
brew completions link

fish -c "mise use -g go@latest"
fish -c "mise use -g java@latest"
fish -c "mise use -g node@latest"
fish -c "mise use -g ruby@latest"
fish -c "mise use -g rust@latest"

grep -q /opt/homebrew/bin/fish /etc/shells \
  || sudo bash -c 'echo /opt/homebrew/bin/fish >> /etc/shells'

# https://stackoverflow.com/a/41553295
dscl . -read ~ UserShell | grep -q /opt/homebrew/bin/fish \
  || chsh -s /opt/homebrew/bin/fish

fish -c "cargo install pks"
fish -c "git submodule update --init --remote"
fish -c "make --directory ${DIR}/etc/nvim/pack/matthewtodd/start/telescope-fzf-native"
fish -c "nvim --headless -c 'helptags ALL' -c quit"
fish -c "npm install -g @anthropic-ai/claude-code"

# https://macos-defaults.com
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock show-recents -bool false
defaults write com.apple.dock static-only -bool true
defaults write com.apple.dock tilesize -int 56
defaults write com.apple.finder FXPreferredViewStyle -string clmv
killall Dock Finder

# https://github.com/Hammerspoon/hammerspoon/pull/582
defaults write org.hammerspoon.Hammerspoon MJConfigFile ${DIR}/etc/hammerspoon/init.lua

swiftc "${DIR}/src/dynamic_desktop.swift" -o "${DIR}/bin/dynamic_desktop"
swiftc "${DIR}/src/set_desktop_image.swift" -o "${DIR}/bin/set_desktop_image"
swiftc "${DIR}/src/terminal_profiles.swift" -o "${DIR}/bin/terminal_profiles"

"${DIR}/bin/dynamic_desktop" "${profile}" "${HOME}/Pictures/Solarized.heic"
# On macOS 14.0, this seems to always select the light (still) version, rather
# than automatically switching.
# "${DIR}/bin/set_desktop_image" "${HOME}/Pictures/Solarized.heic"
"${DIR}/bin/terminal_profiles"

# Why not? This could be fun.
open raycast://confetti
