#!/usr/bin/osascript
# https://stefan.sofa-rockers.org/2018/10/23/macos-dark-mode-terminal-vim/

tell application "System Events"
  if dark mode of appearance preferences then
    set theme to "Solarized Dark"
  else
    set theme to "Solarized Light"
  end if
end tell

tell application "Terminal"
  set default settings to settings set theme
  set current settings of tabs of windows to settings set theme
end tell

# https://vi.stackexchange.com/a/13579
# if we could get a vim compiled with +clientserver, we could ping them all:
# for instance in $(vim --serverlist); do
#   vim --servername $instance --remote-send $'\e:wqa\n'
# done

