#!/usr/bin/osascript

on run argv
  set context to item 1 of argv

  tell application "Things.app"
    repeat with the_to_do in to dos of list "Inbox"
      log the name of the_to_do as string
    end repeat

    repeat with the_to_do in to dos of list "Today"
      if the tag names of the_to_do is equal to "" or the tag names of the_to_do contains context
        log the name of the_to_do as string
      end if
    end repeat

    repeat with the_project in projects whose status is open
      if the tag names of the_project is equal to "" or the tag names of the_project contains context
        if (every to do of the_project whose status is open) is {}
          log "Plan next steps for " & the name of the_project as string & "."
        end if
      end if
    end repeat
  end tell
end
