#!/usr/bin/osascript

on run argv
  set the_result_actual to {}
  set the_result to a reference to the_result_actual

  tell application "Things3"
    tell every to do of list "Inbox" whose status is open
      copy its name to the end of the_result
    end tell

    tell every to do of list "Today" whose status is open
      copy its name to the end of the_result
    end tell
  end tell

  set text item delimiters to {"\n"}
  the_result as string
end
