#!/bin/bash

set -euxo pipefail

export DIR=$(cd `dirname $0`; pwd)

brew update --verbose
brew upgrade --verbose
brew cask upgrade --verbose
brew cleanup --verbose
brew bundle cleanup --force --file=${DIR}/share/Brewfile

fish -c "BUNDLE_PATH='${XDG_DATA_HOME}/vim' bundle update --gemfile=${DIR}/share/Gemfile --all"
fish -c 'vim +PlugUpgrade +PlugClean +PlugUpdate +qall'

swift ${DIR}/libexec/terminal_profiles.swift
