[tools]
go = "latest"
java = "latest"
node = "latest"
ruby = "latest"
rust = "latest"

"cargo:pks" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
