[tools]
go = "latest"
java = "latest"
node = "latest"
ruby = "latest"

"cargo:pks" = "latest"
"gem:ruby-lsp" = "latest"
"gem:sorbet" = "latest"

[tools.rust]
components = "rust-analyzer"
version = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]

[settings.ruby]
compile = false
