" don't bother with vi compatibility
set nocompatible

" early set up various paths roughly according to the XDG spec
set runtimepath+=$XDG_CONFIG_HOME/vim
call xdg#setup()

" set up vim-plug, https://github.com/junegunn/vim-plug
call plug#begin()
Plug 'austintaylor/vim-indentobject'
Plug 'dag/vim-fish'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-unimpaired'
call plug#end()

" general settings
set backupcopy=yes  " see :help crontab
set clipboard=unnamed
set grepformat=%f:%l:%c:%m
set grepprg=ag\ --vimgrep\ $*
set list            " show trailing whitespace
set nohlsearch
set number          " enable line numbering
set ttimeoutlen=-1  " https://github.com/neovim/neovim/issues/2017#issuecomment-75223935
set wildmode=list:longest,full " helpful tab completion

" don't bother prompting to open these files.
set wildignore=log/**,tmp/**,*.rbc

" keyboard shortcuts
let mapleader = ','
nmap <leader>a :grep!<Space>
nmap <leader>b :FZFBuffers<CR>
nmap <leader>h :FZFHelptags<CR>
nmap <leader>t :FZFGFiles<CR>

" colorscheme
silent! colorscheme solarized

" autocommands
augroup vimrc
  autocmd!
  autocmd BufEnter,CursorHold,CursorHoldI,FocusGained * checktime
  autocmd QuickFixCmdPost * cwindow
  autocmd VimResized * wincmd =
augroup END

" plugin settings
let g:fzf_command_prefix = 'FZF'
let g:fzf_layout = { 'down': '10' }
