# vim: set ft=ruby

tap "cockroachdb/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "autoconf"
brew "bazel"
brew "ccache"
brew "cmake"
brew "entr"
brew "fd"
brew "fish"
brew "fswatch"
brew "fzf"
brew "git"
brew "go"
brew "make"
brew "node@12"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "yarn"

brew "cockroachdb/tap/cockroach"

cask "docker"
cask "font-go"
cask "goland"
cask "hammerspoon", greedy: true
cask "raycast", greedy: true
cask "tuple", greedy: true
