autoload -U compinit
mkdir -p ${XDG_CACHE_HOME}/zsh
compinit -d ${XDG_CACHE_HOME}/zsh/zcompdump

source /usr/local/etc/bash_completion.d/git-prompt.sh

export CLICOLOR=yes
export EDITOR=vim
export FZF_DEFAULT_COMMAND='fd --hidden --type f'
export GOROOT=/usr/local/opt/go@1.17/libexec
export LESSHISTFILE=-
export MACOSX_DEPLOYMENT_TARGET=(sw_vers -productVersion)

path=(
  "${HOME}/.local/bin"
  "/usr/local/opt/go@1.17/bin"
  "/usr/local/opt/make/libexec/gnubin"
  "/usr/local/opt/node@16/bin"
  "/usr/local/opt/python@3.9/libexec/bin"
  "/usr/local/opt/ruby/bin"
  "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin"
  $path
)

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
mkdir -p ${XDG_DATA_HOME}/zsh
HISTFILE=${XDG_DATA_HOME}/zsh/history
HISTORY_IGNORE='ls|ls *'

alias vim="nvim"
