# vim: set ft=ruby

tap "homebrew/bundle"

brew "atuin"
brew "awscli"
brew "entr"
brew "fd"
brew "fish"
brew "fswatch"
brew "fzf"
brew "gh"
brew "git"
brew "graphviz"
brew "jq"
brew "lua"
brew "mas"
brew "neovim", args: ["HEAD"]
brew "node"
brew "openjdk"
brew "shellcheck"
brew "terraform"
brew "the_silver_searcher"
brew "tree"

cask "1password"
cask "1password-cli"
cask "discord", greedy: true
cask "hammerspoon", greedy: true
cask "intellij-idea-ce", greedy: true
cask "mimestream", greedy: true
cask "netnewswire", greedy: true
cask "obsidian", greedy: true
cask "raycast", greedy: true
cask "tuple", greedy: true

mas "1Password for Safari", id: 1569813296
mas "GarageBand", id: 682658836
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "Magic Lasso", id: 1198047227
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Things", id: 904280696
mas "Tot", id: 1491071483
mas "Xcode", id: 497799835
mas "iMovie", id: 408981434
