#!/bin/sh

set -eu

ROOT=$(cd "$(dirname "$0")"; cd ..; pwd)
PACK_PATH="etc/nvim/pack/matthewtodd/start"

add() {
  if [ "$#" -ne 1 ]; then
    help
    exit 1
  fi

  PROJECT=$1
  URL="https://github.com/${PROJECT}"
  NAME=$(echo "${PROJECT}" | sed -E -e 's/^.*\///' -e 's/n?vim-//' -e 's/\.n?vim//')
  PLUGIN_PATH="${PACK_PATH}/${NAME}"

  echo "git submodule add --name ${NAME} \\"
  echo "  ${URL} \\"
  echo "  ${PLUGIN_PATH}"
}

branch() {
  if [ "$#" -ne 2 ]; then
    help
    exit 1
  fi

  NAME=$1
  BRANCH=$2

  echo "git config -f .gitmodules submodule.${NAME}.branch ${BRANCH}"
}

help() {
  echo "$(basename "$0") add tpope/vim-sensible"
  echo "$(basename "$0") branch sensible v2.0"
  echo "$(basename "$0") ls"
  echo "$(basename "$0") rm sensible"
}

list() {
  if [ "$#" -ne 0 ]; then
    help
    exit 1
  fi

  ls "${ROOT}/${PACK_PATH}"
}

remove() {
  if [ "$#" -ne 1 ]; then
    help
    exit 1
  fi

  NAME=$1
  PLUGIN_PATH=$(git config -f "${ROOT}/.gitmodules" "submodule.${NAME}.path")

  echo "git rm ${PLUGIN_PATH}"
}

if [ "$#" -eq 0 ]; then
  help
  exit 1
fi

case "$1" in
  add)    shift; add "$@" ;;
  branch) shift; branch "$@" ;;
  help)   shift; help "$@" ;;
  ls)     shift; list "$@" ;;
  rm)     shift; remove "$@" ;;
  *)      shift; help; exit 1 ;;
esac
