# vim: set ft=ruby

tap "cockroachdb/tap"
tap "homebrew/bundle"

brew "autoconf"
brew "awscli"
brew "bash"
brew "bazelisk"
brew "cmake"
brew "entr"
brew "fd"
brew "fish"
brew "fswatch"
brew "fzf"
brew "gh"
brew "git"
brew "go@1.19"
brew "graphviz"
brew "jq"
brew "k3d"
brew "lua"
brew "make"
brew "mas"
brew "neovim", args: ["HEAD"]
brew "node@16"
brew "pre-commit"
brew "shellcheck"
brew "terraform"
brew "the_silver_searcher"
brew "tree"
brew "vault"
brew "yarn"

brew "cockroachdb/tap/cockroach"

cask "1password-cli"
cask "goland", greedy: true
cask "google-cloud-sdk"
cask "hammerspoon", greedy: true
cask "logitech-camera-settings"
# Temporarily disabling so I can manually install 0.41.6-beta.
# cask "mimestream", greedy: true
cask "rancher", greedy: true
cask "raycast", greedy: true
cask "tuple", greedy: true

mas "1Password for Safari", id: 1569813296
mas "Hush", id: 1544743900
mas "Magic Lasso", id: 1198047227
mas "Muse", id: 1501563902
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Simplified for Twitter", id: 1479307973
mas "Things", id: 904280696
mas "Tot", id: 1491071483
mas "Xcode", id: 497799835
